spring:
  cloud:
    gateway:
      routes:
      - id: currencyms
        uri: lb://currencyms
        predicates:
        - Path= /calcurrency
        
      - id: conversionms
        uri: lb://conversionms
        predicates:
        - Path= /conversion
© 2020 GitHub, Inc.
