spring:
  cloud:
    gateway:
     routes:
      - id: conversionms
        uri: lb://CONVERSIONMS
        predicates:
        - Path=/conversion/**
        
        - id: currencyms
        uri: lb://CURRENCYMS
        predicates:
        - Path=/calcurrency/**
